version: v1
kind: kubernetes
application: potato-facts
targets:
  staging:
    account: kals-deployment-cluster
    namespace: kals-deployments
    strategy: rolling
  prod:
    account: kals-deployment-cluster
    namespace: kals-deployments-prod
    strategy: rolling
    constraints:
      dependsOn: ["staging"]
manifests:
  # This tutorial uses URLs to ensure a simple first-time deployment experience.
  # You can also use relative file paths to define manifest locations.
  - path: https://raw.githubusercontent.com/armory-io/cdaas-examples/main/hello-armory/manifests/potato-facts-v1.yaml
  - path: https://raw.githubusercontent.com/armory-io/cdaas-examples/main/hello-armory/manifests/potato-facts-service.yaml
  - path: https://raw.githubusercontent.com/armory-io/cdaas-examples/main/hello-armory/manifests/staging-namespace.yaml
    targets: ["staging"]
  - path: https://raw.githubusercontent.com/armory-io/cdaas-examples/main/hello-armory/manifests/prod-namespace.yaml
    targets: ["prod"]
strategies:
  rolling:
    canary:
      steps:
        - setWeight:
            weight: 100
